# Generated by Django 4.2.14 on 2025-08-08 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_remove_tenant_theme_alter_tenant_domain_and_more'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
