# Generated by Django 5.0.14 on 2025-08-13 18:55

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domainler'},
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=True, verbose_name='Deneme Sürecinde'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=clients.models.one_year_later, verbose_name='Ücretli Bitiş'),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_color',
            field=models.CharField(default='#0ea5e9', max_length=7, verbose_name='Birincil Renk'),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Şema Adı'),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_color',
            field=models.CharField(default='#1e293b', max_length=7, verbose_name='İkincil Renk'),
        ),
    ]
