# Generated by Django 5.0.14 on 2025-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_merge_20250814_1656'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='domain',
            name='domain_lower_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='db_alias',
            field=models.CharField(blank=True, db_index=True, default='default', help_text="Bu tenant'ın verilerinin bulunduğu Django DATABASES alias'ı", max_length=50, null=True, verbose_name='DB Alias'),
        ),
    ]
