# Generated by Django 5.0.14 on 2025-08-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_remove_tenant_domain_alter_tenant_name'),
        ('tenancy', '0002_remove_tenant_theme_alter_tenant_domain_and_more'),
    ]

    operations = [
    ]
